### ISSUE TITLE
new badge

### ISSUE THREAD

**Issue by maximousblk** [nestlandofficial/nest.land#102]
nothing critical but the badge doesn't look that good.

I have made some examples that too are not very good but can be a starting point.

examples: [figma file](https://www.figma.com/file/BN2w0nSbJIxeSxP2PjwW9r/nest)

**Comment by oganexon** [comment]
I like it a lot!
It's true that on the current badge the text is not well rendered.

![image](https://user-images.githubusercontent.com/52361520/85168225-5163e480-b26a-11ea-9346-0cef4f8e67e4.png)

@tbaumer22 Do you see the badge like that, too?

**Comment by tbaumer22** [comment]
@maximousblk I love like those mockups. The current design is inspired by Bower's badge, although I am not against switching to one of the choices you made at all.
![image](https://user-images.githubusercontent.com/20846869/85168929-0da4b700-b239-11ea-937d-8ba232d7167d.png)

@oganexon this is how the badge renders for me: 
![image](https://user-images.githubusercontent.com/20846869/85168867-f82f8d00-b238-11ea-9308-b42b24335d84.png)

**Comment by oganexon** [comment]
@tbaumer22 I get the same result on Firefox and Chrome, this is strange
I'm on Windows btw

**Comment by maximousblk** [comment]
@tbaumer22 should I open a PR?

If yes which one should I include and if there's any thing to change?

**Comment by tbaumer22** [comment]
@oganexon that is really strange. I'm on a Mac. Safari renders fine for me as well. An issue could be my font selection. Perhaps you don't have that installed. A potential fix would be for us to export the text as curves in the SVG so that font rendering isn't an issue. I was viewing it from [https://nest.land/badge.svg](https://nest.land/badge.svg)

@maximousblk I'm gravitating towards either the `full back` or the `full egg` design. I think that the extra padding will be needed around the text as compared to the `small` variants. If I had to pick one, I'd pick the `full egg` option for its simplicity while also throwing in a splash of color in the egg. Either way, I would be happy. The gray background may blend better with other badges as well, if someone has multiple on their repository.

**Comment by maximousblk** [comment]
@oganexon I think the effect is caused by the raster elements included in the SVG

![image](https://user-images.githubusercontent.com/28438021/85169989-59338100-b28a-11ea-90b0-9ffa817e0b60.png)

**Comment by maximousblk** [comment]
new badges:

regular:

![nest badge](https://nest.land/badge.svg)

large:

![nest badge](https://nest.land/badge-large.svg)
