### ISSUE TITLE
[PROPOSAL] Twig - Nest.land's Arweave API Service (private)

### ISSUE THREAD

**Issue by divy-work** [nestlandofficial/nest.land#148]
**What**
-----------

An API for internal use by `X` (node) and `API` (rust). It will perform everything related to Arweave (transactions, signing) etc.
This will not be public and only be used by the public services internally.

**Why**
-----------

Now that we have a Rust API coming up, the major issue is to integrate an Arweave client in Rust. We already have `x-node` which uses `arweave-js` as the client. 
Instead of having 2 different client doing almost the same job..why not have one central service to do that for both of them?

**How**
------------

Twig _should_ be a Node service similar to:
https://github.com/samcamwilliams/hooverd

**Other**
------------

I'm proposing this after spending 3 days of trying to integrate Arweave with Rust...It will not only make our lives easy..We will have a central service for Arweave related stuff.
_The name?_ It's related to nest lol

**Comment by tbaumer22** [comment]
@divy-work I really like this idea for its flexibility. In the near future, we're planning to implement the option for users to use their own Arweave wallets on nest.land instead of uploading through ours. I think that the concept of `twig` will make this easier since the Arweave uploading is kept separate from the public APIs

**Comment by tbaumer22** [comment]
Closing this issue, as it is no longer a proposal 👍
